version: '3.8'

services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  server:
    image: server
    container_name: server
    network_mode: host
    restart: unless-stopped
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    env_file:
      - .env
    volumes:
      - /home/resources:/home/resources

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - /dbdata:/data/db

  fgpt:
    image: fgpt
    container_name: fgpt
    ports:
      - 3003:8501
    restart: unless-stopped

  transformers-playground:
    image: transformers-playground
    container_name: transformers-playground
    ports:
      - 3004:8501
    restart: unless-stopped

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  ollama-webui: {}
